arch:
    - amd64
    - ppc64le
language: emacs-lisp
env:
  matrix:
    - EMACS=emacs-snapshot

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-elisp
  - sudo apt-get update -qq
  - sudo apt-get install -qq $EMACS

script:
  - $EMACS --version
  - $EMACS -Q --batch -L . -l ert -l eshell-up-tests.el -f ert-run-tests-batch-and-exit
